using AutoMapper;

using Domain.Enums;
using Domain.Models;
using Domain.Services.CustomerEditRequests;
using Domain.Services.Tour.Interface;
using Domain.Services.TourBooking.DTO;
using Domain.Services.TourBooking.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using TourBooking.API.TourBooking.RequestObjects;
using TourBooking.Controllers;




namespace TourBooking.API.TourBooking
{
   
    [ApiController]
    [Route("api/v1/[controller]")]
    public class TourBookingController : BaseApiController<TourBookingController>
    {
        private readonly ITourBookingService _service;
        private readonly ITourService _tourService;
        private readonly IMapper _mapper;
        private readonly ITourBookingEditRequestService _editRequest;
        private readonly TourBookingPdfService _pdf;

        public TourBookingController(ITourBookingService service, IMapper mapper,ITourService tourService, ITourBookingEditRequestService editrequest, TourBookingPdfService pdfService)
        {
            _service = service;
            _mapper = mapper;
            _tourService = tourService;
            _editRequest = editrequest;
            _pdf = pdfService;
        }

        [Authorize(Roles = "AGENCY,CUSTOMER,CONSULTANT")]
        [HttpPost]
       public async Task<IActionResult> AddTourBooking([FromBody] AddTourBookingRequest request)
        {
            
            var dto = new TourBookingDto
            {
                //Id will be generated by service or database
                TourId = request.TourId,
                UserId=request.UserId,
                FirstName = request.FirstName,
                LastName = request.LastName,
                Gender = request.Gender,
                Dob = request.Dob,
                Citizenship = request.Citizenship,
                PassportNumber = request.PassportNumber,
                IssueDate = request.IssueDate,
                ExpiryDate = request.ExpiryDate,
                PlaceOfBirth = request.PlaceOfBirth,
                LeadPassenger = request.LeadPassenger,
                ParticipantType = request.ParticipantType,
                Status = request.Status
            };

            var result = await _service.AddTourBookingAsync(dto);

            // return 201 Created with route to a “GetById” action
            return CreatedAtAction(nameof(GetTourBookingById),
                new { id = result.Id }, result);
        }

        [Authorize(Roles = "AGENCY,CUSTOMER,CONSULTANT")]
        [HttpGet("booking/{id}")]
        public async Task<IActionResult> GetTourBookingById(Guid id)
        {
            var booking = await _service.GetTourBookingByIdAsync(id);
            return booking == null ? NotFound() : Ok(booking);
        }

        [Authorize(Roles = "AGENCY,CONSULTANT")]
        [HttpGet("tour/{tourId}")]
        public async Task<IActionResult> GetByTourId(Guid tourId)
            => Ok(await _service.GetTourBookingsByTourIdAsync(tourId));

        [Authorize(Roles = "AGENCY,CONSULTANT")]
        [HttpGet]
        public async Task<IActionResult> GetAllTourBookings()
        {
            var result = await _service.GetAllTourBookingsAsync();
            return Ok(result);
        }

        [Authorize(Roles = "AGENCY,CONSULTANT,CUSTOMER")]
        [HttpPut("{id}")]
        public async Task<IActionResult> UpdateTourBooking(Guid id, [FromBody] UpdateTourBookingDto dto)
        {
            var role = User.FindFirst(ClaimTypes.Role)?.Value;
            var bk = await _service.GetTourBookingByIdAsync(id);
            // If CUSTOMER tries to update
            if (role == "CUSTOMER")
            {
       
                if (bk.EditStatusCheck== "ApprovedForEdit" && bk.IsEditAllowed==true)
                {
                    var update = await _service.UpdateTourBookingAsync(id, dto);
                    await _service.MarkEditCompleteAsync(id);
                    return update == null ? NotFound() : Ok(update);
                }
                else
                {
                    // Call RequestEdit here
                    var userIdString = User.FindFirst("UserId")?.Value;
                    var userId = Guid.Parse(userIdString);

                    await _service.RequestEditAsync(id, userId, "Customer requested edit.");

                    return Ok(new { message = "Edit request sent to agency for approval." });
                }
            }

            // If AGENCY or CONSULTANT is updating
            if (role == "AGENCY"||role=="CONSULTANT")
            {
                var updated = await _service.UpdateTourBookingAsync(id, dto);
                return updated == null ? NotFound() : Ok(updated);
            }
            return BadRequest();
        }

        [Authorize(Roles = "AGENCY,CONSULTANT")]
        [HttpPatch("{id}")]
        public async Task<IActionResult> PatchTourBookingStatus(Guid id,
            [FromBody] PatchTourBookingDto dto)
        {
            var patched = await _service.PatchTourBookingAsync(id, dto);
            return patched == null ? NotFound() : Ok(patched);
        }

        [Authorize(Roles = "AGENCY,CONSULTANT")]
        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var success = await _service.DeleteTourBookingAsync(id);
            if (!success) return NotFound();
            return Ok(new { message = "Booking deleted successfully" });
        }

        [Authorize(Roles = "CUSTOMER,AGENCY,CONSULTANT")]
        [HttpGet("user/{userId}")]
        public async Task<IActionResult> GetByUserId(Guid userId)
        {
            var result = await _service.GetTourBookingsByUserIdAsync(userId);
           
            
            if (!result.Any()) return NotFound(new { message = "No bookings found for this user." });

            
            return Ok(result);

        }
       
        [Authorize(Roles = "AGENCY,CONSULTANT")]
        [HttpPatch("{bookingId}/Approve-edit")]
        public async Task<IActionResult> TourBookingApproveEdit(Guid bookingId)
        {
            await _service.ApproveEditAsync(bookingId);
          
            return Ok(new { message = "Customer is now allowed to edit the booking." });
        }
        [Authorize(Roles = "AGENCY,CONSULTANT")]
        [HttpGet("Pending-edits")]
        public async Task<IActionResult> GetTourBookingPendingEditRequests()
        {
            var requests = await _editRequest.GetPendingRequestsAsync();
            return Ok(requests);
        }

        [Authorize(Roles = "CUSTOMER,AGENCY,CONSULTANT")]
        [HttpPatch("{id}/cancel")]
        public async Task<IActionResult> CancelBooking(Guid id, [FromBody] CancelBookingDto request)
        {
            var role = User.FindFirst(ClaimTypes.Role)?.Value;

            var booking = await _service.GetTourBookingByIdAsync(id);
            if (booking == null)
                return NotFound(new { message = "Booking not found" });

            // CUSTOMER can cancel ONLY their own booking
            if (role == "CUSTOMER")
            {
                var userIdString = User.FindFirst("UserId")?.Value;
                var userId = Guid.Parse(userIdString);

                if (booking.UserId != userId)
                    return Unauthorized(new { message = "You can only cancel your own booking." });
            }

            var result = await _service.CancelBookingAsync(id, request.Reason);

            if (!result)
                return BadRequest(new { message = "Booking cancellation failed." });

            return Ok(new { message = "Booking cancelled successfully." });
        }

        [Authorize(Roles = "AGENCY,CONSULTANT")]
        [HttpGet("cancelled")]
        public async Task<IActionResult> GetCancelledBookings()
        {
            var result = await _service.GetCancelledBookingsAsync();
            return Ok(result);
        }

        [Authorize(Roles = "AGENCY,CUSTOMER,CONSULTANT")]
        [HttpGet("booking/{id}/document")]
        public async Task<IActionResult> GetDocument(Guid id)
        {
            var booking = await _service.GetTourBookingByIdAsync(id);
            if (booking == null) return NotFound();

            var pdf = _pdf.GenerateBookingPdf(booking);

            return File(pdf, "application/pdf", $"Booking-{id}.pdf");
        }


        [HttpPost("booking/{id}/send-document")]
        public async Task<IActionResult> SendDocument(Guid id)
        {
            var booking = await _service.GetTourBookingByIdAsync(id);
            if (booking == null) return NotFound();

            await _service.SendBookingDocumentAsync(booking);

            return Ok("Booking PDF document sent to the customer.");
        }


    }
}






